-- Production-safe placeholder.
--
-- Synthetic fixtures live in supabase/tests/seed.synthetic.sql and are never
-- applied by the hosted deployment workflow. Production data is synchronized
-- only through `pnpm sync:curated-data` from a reviewed CURATED_DATA_DIR.
