-- Forward-only confidence evidence. `projects.confidence_level` remains legacy
-- research metadata and must never determine rank eligibility.

create table project_confidence_evidence (
  id bigint generated by default as identity primary key,
  calculation_run_id uuid not null references calculation_runs(id),
  project_id uuid not null references projects(id),
  component text not null check (component in (
    'founder_identity_evidence',
    'founder_wallet_coverage',
    'team_foundation_treasury_coverage',
    'circulation_treatment',
    'funding_completeness',
    'market_reliability'
  )),
  maximum_score numeric(5, 2) not null check (maximum_score > 0),
  score numeric(5, 2) not null check (score >= 0 and score <= maximum_score),
  complete boolean not null,
  evidence jsonb not null default '[]'::jsonb
    check (jsonb_typeof(evidence) = 'array'),
  created_at timestamptz not null default now(),
  unique (calculation_run_id, project_id, component)
);

create index project_confidence_evidence_project_id_idx
  on project_confidence_evidence(project_id);

alter table project_confidence_evidence enable row level security;

comment on column projects.confidence_level is
  'Legacy research metadata. SQL-derived confidence evidence controls eligibility.';

do $migration$
declare
  function_definition text;
  inputs_start integer;
  founding_units_start integer;
  replacement text := $replacement$
  ), inputs as (
    select
      p.id as project_id,
      a.id as asset_id,
      m.id as market_observation_id,
      m.price_usd,
      m.circulating_supply,
      m.market_cap_usd,
      m.observed_at as market_observed_at,
      m.fetched_at as market_fetched_at,
      m.source_url as market_source_url,
      m.source_description as market_source_description,
      coalesce(w.excluded_supply, 0) as excluded_supply,
      coalesce(m.price_usd * w.excluded_supply, 0) as excluded_value_usd,
      coalesce(w.required_count, 0) as required_wallet_count,
      coalesce(w.observed_count, 0) as observed_wallet_count,
      coalesce(w.all_reviewed, true) as all_wallet_rows_reviewed,
      p.wallet_review_status,
      p.wallet_review_reviewer,
      p.wallet_review_reviewed_at,
      p.wallet_review_notes,
      p.wallet_review_evidence_source_ids,
      coalesce(f.required_count, 0) as required_funding_count,
      coalesce(f.all_reviewed, true) as all_funding_reviewed,
      coalesce(f.capital_raised, 0) as capital_raised,
      p.funding_review_status,
      p.funding_review_reviewer,
      p.funding_review_reviewed_at,
      p.funding_review_notes,
      p.funding_review_evidence_source_ids,
      exists (
        select 1
        from project_founding_units as pfu
        where pfu.project_id = p.id
      ) as has_founding_unit_attribution,
      coalesce((
        select jsonb_agg(jsonb_build_object(
          'foundingUnitId', pfu.founding_unit_id,
          'attributionFraction', pfu.attribution_fraction,
          'attributionMethod', pfu.attribution_method
        ) order by pfu.founding_unit_id)
        from project_founding_units as pfu
        where pfu.project_id = p.id
      ), '[]'::jsonb) as founding_unit_evidence
    from projects as p
    join assets as a on a.project_id = p.id and a.is_primary and a.is_active
    left join latest_market as m on m.asset_id = a.id
    left join wallet_rollup as w on w.asset_id = a.id
    left join funding_rollup as f on f.project_id = p.id
    where p.status = 'active'
      and p.calculation_category = 'liquid_token'
  ), evaluated as (
    select
      *,
      (
        market_observation_id is not null
        and price_usd > 0
        and circulating_supply >= 0
        and market_observed_at >= now() - interval '20 minutes'
      ) as market_ready,
      (
        wallet_review_status = 'approved_sufficient'
        and wallet_review_reviewer is not null
        and wallet_review_reviewed_at is not null
        and jsonb_array_length(wallet_review_evidence_source_ids) > 0
        and all_wallet_rows_reviewed
      ) as wallet_ready,
      (
        funding_review_status = 'approved_sufficient'
        and funding_review_reviewer is not null
        and funding_review_reviewed_at is not null
        and jsonb_array_length(funding_review_evidence_source_ids) > 0
        and all_funding_reviewed
      ) as funding_ready
    from inputs
  ), confidence_components as (
    select
      *,
      jsonb_build_array(
        jsonb_build_object(
          'component', 'founder_identity_evidence',
          'maximum_score', 20,
          'score', case when wallet_ready then 20 else 0 end,
          'complete', wallet_ready,
          'evidence', jsonb_build_array(jsonb_build_object(
            'foundingUnits', founding_unit_evidence
          ))
        ),
        jsonb_build_object(
          'component', 'founder_wallet_coverage',
          'maximum_score', 20,
          'score', case when wallet_ready then 20 else 0 end,
          'complete', wallet_ready,
          'evidence', jsonb_build_array(jsonb_build_object(
            'reviewStatus', wallet_review_status,
            'requiredWalletCount', required_wallet_count,
            'observedWalletCount', observed_wallet_count,
            'sourceIds', wallet_review_evidence_source_ids
          ))
        ),
        jsonb_build_object(
          'component', 'team_foundation_treasury_coverage',
          'maximum_score', 15,
          'score', case when wallet_ready and all_wallet_rows_reviewed then 15 else 0 end,
          'complete', wallet_ready and all_wallet_rows_reviewed,
          'evidence', jsonb_build_array(jsonb_build_object(
            'reviewedWalletRows', observed_wallet_count,
            'requiredWalletCount', required_wallet_count
          ))
        ),
        jsonb_build_object(
          'component', 'circulation_treatment',
          'maximum_score', 15,
          'score', case
            when market_ready and wallet_ready
              and excluded_supply <= circulating_supply then 15
            else 0
          end,
          'complete', market_ready and wallet_ready
            and excluded_supply <= circulating_supply,
          'evidence', jsonb_build_array(jsonb_build_object(
            'excludedSupply', excluded_supply,
            'circulatingSupply', circulating_supply,
            'marketObservationId', market_observation_id
          ))
        ),
        jsonb_build_object(
          'component', 'funding_completeness',
          'maximum_score', 15,
          'score', case when funding_ready then 15 else 0 end,
          'complete', funding_ready,
          'evidence', jsonb_build_array(jsonb_build_object(
            'reviewStatus', funding_review_status,
            'requiredFundingCount', required_funding_count,
            'allFundingReviewed', all_funding_reviewed
          ))
        ),
        jsonb_build_object(
          'component', 'market_reliability',
          'maximum_score', 15,
          'score', case when market_ready then 15 else 0 end,
          'complete', market_ready,
          'evidence', jsonb_build_array(jsonb_build_object(
            'marketObservationId', market_observation_id,
            'observedAt', market_observed_at,
            'fetchedAt', market_fetched_at,
            'sourceUrl', market_source_url
          ))
        )
      ) as confidence_components
    from evaluated
  ), confidence_rollup as (
    select
      *,
      coalesce((
        select sum((component ->> 'score')::numeric)
        from jsonb_array_elements(confidence_components) as component
      ), 0) as confidence_score,
      coalesce((
        select bool_and((component ->> 'complete')::boolean)
        from jsonb_array_elements(confidence_components) as component
      ), false) as confidence_complete
    from confidence_components
  ), final as (
    select
      *,
      case
        when not confidence_complete or confidence_score < 40 then 'insufficient'
        when confidence_score < 60 then 'low'
        when confidence_score < 80 then 'medium'
        else 'high'
      end as confidence_label
    from confidence_rollup
  )
  insert into project_scores (
    calculation_run_id,
    project_id,
    asset_id,
    price_usd,
    circulating_supply,
    market_cap_usd,
    excluded_supply,
    excluded_value_usd,
    capital_raised_usd,
    outside_holder_supply,
    outside_holder_value_usd,
    score_usd,
    confidence_label,
    market_observation_id,
    data_freshness,
    calculation_breakdown,
    warnings,
    eligibility_status,
    ineligibility_reasons
  )
  select
    v_run_id,
    project_id,
    asset_id,
    price_usd,
    circulating_supply,
    case when market_ready then price_usd * circulating_supply end,
    case when wallet_ready then excluded_supply end,
    case when market_ready and wallet_ready then excluded_value_usd end,
    case when funding_ready then capital_raised end,
    case
      when market_ready and wallet_ready
      then circulating_supply - excluded_supply
    end as outside_holder_supply,
    case
      when market_ready and wallet_ready
      then (circulating_supply - excluded_supply) * price_usd
    end as outside_holder_value_usd,
    case
      when market_ready
        and wallet_ready
        and funding_ready
        and confidence_label <> 'insufficient'
        and excluded_supply <= circulating_supply
      then (price_usd * circulating_supply) - excluded_value_usd - capital_raised
      else null
    end as score_usd,
    confidence_label,
    market_observation_id,
    jsonb_build_object(
      'marketObservedAt', market_observed_at,
      'marketFetchedAt', market_fetched_at,
      'marketSourceUrl', market_source_url,
      'marketSourceDescription', market_source_description
    ),
    jsonb_build_object(
      'excludedSupply', excluded_supply,
      'excludedValueUsd', excluded_value_usd,
      'capitalRaisedUsd', capital_raised,
      'walletReviewStatus', wallet_review_status,
      'fundingReviewStatus', funding_review_status,
      'confidence', jsonb_build_object(
        'score', confidence_score,
        'label', confidence_label,
        'complete', confidence_complete,
        'components', confidence_components
      )
    ),
    case
      when market_ready
        and wallet_ready
        and funding_ready
        and confidence_label <> 'insufficient'
        and excluded_supply <= circulating_supply
      then '[]'::jsonb
      else jsonb_build_array('Research inputs are incomplete; project remains unranked.')
    end,
    case
      when market_ready
        and wallet_ready
        and funding_ready
        and confidence_label <> 'insufficient'
        and excluded_supply <= circulating_supply
      then 'ranked'
      else 'research_in_progress'
    end,
    array_to_json(array_remove(array[
      case when not market_ready then 'Current market observation is incomplete.' end,
      case when not wallet_ready then 'Wallet review evidence is incomplete.' end,
      case when not funding_ready then 'Funding review evidence is incomplete.' end,
      case when confidence_label = 'insufficient' then 'SQL-derived confidence evidence is incomplete or insufficient.' end,
      case when excluded_supply > circulating_supply then 'Excluded supply exceeds circulating supply.' end
    ], null))::jsonb
  from final;

  insert into project_confidence_evidence (
    calculation_run_id,
    project_id,
    component,
    maximum_score,
    score,
    complete,
    evidence
  )
  select
    v_run_id,
    project_id,
    component.component,
    component.maximum_score,
    component.score,
    component.complete,
    component.evidence
  from project_scores as scores
  cross join lateral jsonb_to_recordset(
    coalesce(
      scores.calculation_breakdown -> 'confidence' -> 'components',
      '[]'::jsonb
    )
  ) as component(
    component text,
    maximum_score numeric,
    score numeric,
    complete boolean,
    evidence jsonb
  )
  where scores.calculation_run_id = v_run_id;
$replacement$;
begin
  function_definition := pg_get_functiondef(
    'recalculate_rankings(text)'::regprocedure
  );
  inputs_start := position('  ), inputs as (' in function_definition);
  founding_units_start := position('  with previous as (' in function_definition);

  if inputs_start = 0 or founding_units_start = 0
    or founding_units_start <= inputs_start then
    raise exception 'Unable to locate ranking inputs in recalculate_rankings';
  end if;

  function_definition :=
    substring(function_definition from 1 for inputs_start - 1)
    || replacement
    || substring(function_definition from founding_units_start);

  execute function_definition;
end;
$migration$;
